### ISSUE TITLE
Non-fatal versions of lookups

### ISSUE THREAD

**Issue by robbat2** [dalen/puppet-dnsquery#8]
Please make it possible to have non-fatal lookups if a record does not exist.

if(defined(dns_aaaa(hostname))) {
  # extra resource for v6 host
}

**Comment by dalen** [comment]
This is fixed in the recently released version 3.0.0, by allowing you to supply a lambda with a default value in case the lookup fails.

For example:
```puppet
$ipv6 = dns_aaaa('hostname.example.com') || { ['::1'] }
```
